# Copyright (c) 2020, 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

title: "OCI APEX Implemenation using Customer Managed ORDS"
description: "Highly Available/Scalable architecuture running APEX in OCI with Customer Managed ORDS"
informationalText: "This IaC supports 5 different size configurations: ALF (Always Free), S, M, L, XL with variations to the general architecture."
schemaVersion: 1.0.0
version: "20210901"

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - tenancy_ocid
    - compartment_ocid
    - region
    visible: false

  - title: "General Configuration"
    variables:
    - proj_abrv
    - size
    - adb_license_model

  - title: "Extras Hidden"
    variables:
      - user_ocid
      - fingerprint
      - private_key_path
    visible: false

  - title: "OCI Services Hidden"
    variables:
      - adb_cpu_core_count
      - adb_dataguard
      - flex_lb_min_shape
      - flex_lb_max_shape
      - compute_instances
      - compute_flex_shape_ocpus
      - adb_storage_size_in_tbs
      - adb_db_version
      - compute_os
      - linux_os_version
      - bastion_user
      - vcn_cidr
      - vcn_is_ipv6enabled
      - public_subnet_cidr
      - private_subnet_cidr
    visible: false

  - title: "Locals Hidden"
    variables:
      - compute_flexible_shapes
      - is_always_free
      - adb_private_endpoint
      - compute_shape
      - is_flexible_shape
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  proj_abrv:
    type: string
    title: "Resource Name Prefix"
    required: true

  size:
    type: enum
    title: "Architecture Size"
    default: "ALF"
    enum:
      - ALF
      - S
      - M
      - L
      - XL
    required: true

  adb_license_model:
    type: enum
    title: "ADB License"
    default: "BRING_YOUR_OWN_LICENSE"
    enum:
      - BRING_YOUR_OWN_LICENSE
      - LICENSE_INCLUDED
    required: true
